from .deepinversion import DeepInvSyntheiszer
from .generative import GenerativeSynthesizer
from .contrastive import CMISynthesizer
from .base import BaseSynthesis
from .dfat import DFATSynthesizer
from .cgan_dfat import DFATCGanSynthesizer
from .sgan_dfat import DFATSGanSynthesizer
from .wgan_dfat import DFATWGanSynthesizer
from .spaceshipnet import Spaceshipnet